#!/bin/bash

jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
git config --global user.name "Dan Lichtenstein"
git config --global user.email lichtenstein.dan@gmail.com
